### PR TITLE
Graphics choice

### PR DESCRIPTION
**Pull request by ranzenTom**
Added a new parameters "graphics" to FlappyBird class. 
FlappyBird(graphics="fancy") will generate the game with changing background, pipes and birds colors.
FlappyBird(graphics="fixed") which is equivalent to FlappyBird() will generate the game with a black background, a red bird and green pipes.

I have created two assets folders, one containing the "fancy pictures" and the other containing the "fixed pictures". Then, the code loads the right folder with respect to the "graphics" parameter. I didn't find another way to add this choice without considerably modifying the code.

I have tested it and it seems to work on my computer.

Good evening :)

### CODE REVIEW

**Comment by erachelson** [comment]
Yup.
I've pulled and I'm checking this morning. Will maybe have some suggestions.
Thanks Thomas!

**Comment by erachelson** [comment]
In order to avoid having 2 folders with almost the same images (and somehow confusing names), I made the following changes:
- brought all images back into "assets" and added a "background-blank.png" file.
- added attribute self.graphics to the FlappyBird class.
- edited the init() method of the FlappyBird class so that the correct pictures are loaded depending on the self.graphics attribute.
I've pushed to a ranzenTom-graphics_choice branch in the upstream repo. Can somebody (Thomas?) quickly review the code before I merge?

**Comment by ranzenTom** [comment]
I am on it :)

**Comment by ranzenTom** [comment]
Nice! The code seems correct and it works on my computer.
Thank you for the corrections, the code is more clear that way.

**Pull request merged**
